# Generated by Django 5.1.2 on 2024-12-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='max_members',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil'), ('veryhard', 'Muito Difícil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
    ]
