# Generated by Django 5.1.2 on 2024-12-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_studygroup_max_members_task_due_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Fácil (10 a 30 min)'), (2, 'Médio (30 min a 1h30)'), (4, 'Difícil (1h30 a 3h)'), (6, 'Muito Difícil (Acima de 3h)')]),
        ),
    ]
